### ISSUE TITLE
Adjust extension metadata

### ISSUE THREAD

**Issue by emmanuelbernard** [spinscale/quarkus-logging-ecs#1]
The current metadata is

```
name: "ECS Logging for Quarkus (Elastic Common Schema)"
metadata:
  keywords:
  - "logging"
  - "json"
  - "formatter"
  - "ecs"
  categories:
  - "external"
  status: "preview"
  guide: "https://github.com/spinscale/quarkus-logging-ecs"
```

I recommend you change the category to  "core", we don't have an "external" extension.
The `guide` is ideally a adoc file that we can publish under https://quarkus.io/guides/  (the URL will be that one). Do you have such a guide?

```
---
name: "ECS Logging for Quarkus (Elastic Common Schema)"
metadata:
  categories:
  - "external"
  status: "preview"
  guide: "https://github.com/spinscale/quarkus-logging-ecs"
```

Don't use keywords, it's only for special cases
